# Generated by Django 5.0.1 on 2024-01-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_genres_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('wishlist', 'Wishlist'), ('currently-reading', 'Currently Reading'), ('finished', 'Finished')], default='wishlist', max_length=20),
        ),
    ]
